// <auto-generated />
namespace AlutechShopDiploma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Weight_for_rollers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Weight_for_rollers));
        
        string IMigrationMetadata.Id
        {
            get { return "202104131356556_Weight_for_rollers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
