// <auto-generated />
namespace AlutechShopDiploma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class New_fields_of_user_message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_fields_of_user_message));
        
        string IMigrationMetadata.Id
        {
            get { return "202104261101533_New_fields_of_user_message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
