//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlutechShopDiploma.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlutechShopDiploma.Resources.Views.Home.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для подачи заяки перейдите в личный кабинет в раздел &apos;Статистика&apos; и кликните по ссылке &apos;Подать заяку на разблокировку&apos;..
        /// </summary>
        public static string AskToUnblock1 {
            get {
                return ResourceManager.GetString("AskToUnblock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подать заявку на разблокировку можно также и через контактную форму на главной странице, указав в теме сообщения &apos;Разблокировка аккаунта&apos; и свою почту..
        /// </summary>
        public static string AskToUnblock2 {
            get {
                return ResourceManager.GetString("AskToUnblock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассмотрение заявки занимает некоторое время. Если заявка будет рассмотрена в положительную сторону, вам придёт на почту, которую вы указали при регистрации, сообщение об успешной разблокировке, если в отрицательную, то на вашу почту придёт сообщение о причине..
        /// </summary>
        public static string AskToUnblock3 {
            get {
                return ResourceManager.GetString("AskToUnblock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила подачи заявки на разблокировку аккаунта.
        /// </summary>
        public static string AskToUnblockLabel {
            get {
                return ResourceManager.GetString("AskToUnblockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГК «АЛЮТЕХ» — крупный производственно-сбытовой холдинг с 22-летней историей. Один из лидеров рынка роллетных систем и секционных ворот в Западной и Восточной Европе, ведущий производитель алюминиевых профильных систем на территории СНГ..
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внушительные производственные мощности позволяют выпускать профили, комплектующие и системы управления для роллет..
        /// </summary>
        public static string Info10 {
            get {
                return ResourceManager.GetString("Info10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алюмин Техно.
        /// </summary>
        public static string Info11 {
            get {
                return ResourceManager.GetString("Info11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инновационное производство по изготовлению, порошковой окраске и анодированию алюминиевых профилей, ставшее самым крупным в СНГ..
        /// </summary>
        public static string Info12 {
            get {
                return ResourceManager.GetString("Info12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старейшим направлением деятельности ГК «АЛЮТЕХ» является выпуск роллет. Они изготавливаются из энергоэффективных пенозаполненных или сверхпрочных экструдированных профилей. Для защиты дома от насекомых, тополиного пуха и пыли предусмотрены роллеты со встроенной антимоскитной сеткой..
        /// </summary>
        public static string Info13 {
            get {
                return ResourceManager.GetString("Info13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кроме того, в ассортименте холдинга представлены роллетные ворота, которые устанавливаются в гаражах и паркингах, а также роллетные решетки для бутиков и торговых центров. Для объектов с повышенными требованиями к безопасности «АЛЮТЕХ» предлагает роллеты с классом взломостойкости P5..
        /// </summary>
        public static string Info14 {
            get {
                return ResourceManager.GetString("Info14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повышенным спросом пользуются секционные ворота. Среди моделей для установки в частных гаражах можно найти бюджетные и премиальные серии. Промышленные ворота также представлены в разных ценовых категориях. Они подходят для установки на СТО, сельскохозяйственных предприятиях и т.д. Для автосалонов и объектов в стиле hi-tech отлично подойдут панорамные ворота..
        /// </summary>
        public static string Info15 {
            get {
                return ResourceManager.GetString("Info15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГК «АЛЮТЕХ» предлагает различные изделия въездной группы. Среди них откатные и распашные ворота, калитки и секции ограждения. Собственное производство гарантирует высокое качество данных изделий. Сочетаемость продукции с экстерьером любого объекта обеспечивается за счет широкого выбора вариантов заполнения. В их числе — сэндвич-панели, алюминиевые профили, роллетные профили и комбинации этих материалов..
        /// </summary>
        public static string Info16 {
            get {
                return ResourceManager.GetString("Info16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для обеспечения комфортного и безопасного управления защитными системами «АЛЮТЕХ» предлагает собственную линейку концептуальной автоматики для роллет, секционных и въездных ворот, а также автоматические шлагбаумы с высокой интенсивностью работы для регулирования проезда на частную территорию..
        /// </summary>
        public static string Info17 {
            get {
                return ResourceManager.GetString("Info17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для повышения эффективности работы складских и логистических центров налажен выпуск современного перегрузочного оборудования..
        /// </summary>
        public static string Info18 {
            get {
                return ResourceManager.GetString("Info18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для реализации интерьерных и архитектурных проектов холдинг предлагает алюминиевые профильные системы..
        /// </summary>
        public static string Info19 {
            get {
                return ResourceManager.GetString("Info19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Крупнейшие заводы холдинга находятся в Минске:.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алютех воротные системы.
        /// </summary>
        public static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алютех Икорпорейтед.
        /// </summary>
        public static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алюмин Техно.
        /// </summary>
        public static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алютех воротные системы.
        /// </summary>
        public static string Info6 {
            get {
                return ResourceManager.GetString("Info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основное направление деятельности — производство секционных ворот. Предприятие способно выпускать около 670 изделий в сутки..
        /// </summary>
        public static string Info7 {
            get {
                return ResourceManager.GetString("Info7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь также изготавливаются сэндвич-панели, комплектующие и продукция из алюминиевых сплавов методом литья под давлением..
        /// </summary>
        public static string Info8 {
            get {
                return ResourceManager.GetString("Info8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алютех Икорпорейтед.
        /// </summary>
        public static string Info9 {
            get {
                return ResourceManager.GetString("Info9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О Группе компаний «АЛЮТЕХ».
        /// </summary>
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каждый товар оценивается по шкале от 1 до 10..
        /// </summary>
        public static string MarksRules1 {
            get {
                return ResourceManager.GetString("MarksRules1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каждый товар может быть оценён одним пользователь только 1 раз..
        /// </summary>
        public static string MarksRules2 {
            get {
                return ResourceManager.GetString("MarksRules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свою оценку можно удалить и оценить товар заново..
        /// </summary>
        public static string MarksRules3 {
            get {
                return ResourceManager.GetString("MarksRules3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокированный пользователь не может оценивать товары..
        /// </summary>
        public static string MarksRules4 {
            get {
                return ResourceManager.GetString("MarksRules4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила оценки товаров.
        /// </summary>
        public static string MarksRulesCaption {
            get {
                return ResourceManager.GetString("MarksRulesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При отправке сообщения необходимо в обязательном порядке указать своё имя, почту, телефон и текст сообщения..
        /// </summary>
        public static string MessagesRules1 {
            get {
                return ResourceManager.GetString("MessagesRules1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обращаем внимание! Ответ на ваше сообщение придёт именно на ту почту, которую вы указывали в форме при отправке сообшений..
        /// </summary>
        public static string MessagesRules2 {
            get {
                return ResourceManager.GetString("MessagesRules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила отправки сообщений для администрации.
        /// </summary>
        public static string MessagesRulesCaption {
            get {
                return ResourceManager.GetString("MessagesRulesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупать можно любой товар неограниченное количество раз..
        /// </summary>
        public static string PurchasesRules1 {
            get {
                return ResourceManager.GetString("PurchasesRules1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупать можно только то максимальное количество товара, которое имеется на складе. Мы ведём работу на данный момент над реализацией предзаказов в нашем магазине..
        /// </summary>
        public static string PurchasesRules2 {
            get {
                return ResourceManager.GetString("PurchasesRules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальное количество товаров для покупки - 1..
        /// </summary>
        public static string PurchasesRules3 {
            get {
                return ResourceManager.GetString("PurchasesRules3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средства на бонусный счёт зачисляются только после подтверждения администратором оплаты заказа..
        /// </summary>
        public static string PurchasesRules4 {
            get {
                return ResourceManager.GetString("PurchasesRules4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма к зачислению на бонусный зависит от стоимости вашего заказа (посмотреть можно при оформлении заказа в разделе &apos;Бонусный счёт&apos;)..
        /// </summary>
        public static string PurchasesRules5 {
            get {
                return ResourceManager.GetString("PurchasesRules5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед списанием средств с бонусного счёта убедитесь, что ваш заказ принял окончательную форму. При списании средств с бонусного счёта и последующем редактировании заказа средсва с бонусного счёта пропадут..
        /// </summary>
        public static string PurchasesRules6 {
            get {
                return ResourceManager.GetString("PurchasesRules6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При оформлении заказа обязательными полями являются контактное имя, номер телефона и электронная почта..
        /// </summary>
        public static string PurchasesRules7 {
            get {
                return ResourceManager.GetString("PurchasesRules7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После оформления заказа и отправки его нам, вы не сможете его редактировать, но сможете его отменить, отправив ИД заказа нам через контактную форму на главной странице для отмены. ИД вашего заказа можно узнать в своём личном кабинете в разделе &apos;Мои заказы&apos;..
        /// </summary>
        public static string PurchasesRules8 {
            get {
                return ResourceManager.GetString("PurchasesRules8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила покупки товаров.
        /// </summary>
        public static string PurchasesRulesCaption {
            get {
                return ResourceManager.GetString("PurchasesRulesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы можно писать неограниченное количество раз на любой товар..
        /// </summary>
        public static string ReviewsRules1 {
            get {
                return ResourceManager.GetString("ReviewsRules1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В отзывах запрещается: нецензурная лексика, спам, любого вида оскорбления, любого вида рознь..
        /// </summary>
        public static string ReviewsRules2 {
            get {
                return ResourceManager.GetString("ReviewsRules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За невыполнение правил - блокировка..
        /// </summary>
        public static string ReviewsRules3 {
            get {
                return ResourceManager.GetString("ReviewsRules3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокированный пользователь не может писать отзывы..
        /// </summary>
        public static string ReviewsRules4 {
            get {
                return ResourceManager.GetString("ReviewsRules4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила написания отзывов.
        /// </summary>
        public static string ReviewsRulesCaption {
            get {
                return ResourceManager.GetString("ReviewsRulesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акционные товары на.
        /// </summary>
        public static string TabName1 {
            get {
                return ResourceManager.GetString("TabName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальные предложения.
        /// </summary>
        public static string TabName1Caption {
            get {
                return ResourceManager.GetString("TabName1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила интернет-магазина.
        /// </summary>
        public static string TabName2 {
            get {
                return ResourceManager.GetString("TabName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеоролики о компании.
        /// </summary>
        public static string TabName2Caption {
            get {
                return ResourceManager.GetString("TabName2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеоматериалы.
        /// </summary>
        public static string TabName3 {
            get {
                return ResourceManager.GetString("TabName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string TabName4 {
            get {
                return ResourceManager.GetString("TabName4", resourceCulture);
            }
        }
    }
}
