//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlutechShopDiploma.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlutechShopDiploma.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости и акции.
        /// </summary>
        public static string NewsAndActionsLabel1 {
            get {
                return ResourceManager.GetString("NewsAndActionsLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочитать новости и действующие акции вы можете здесь..
        /// </summary>
        public static string NewsAndActionsLabel2 {
            get {
                return ResourceManager.GetString("NewsAndActionsLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узнать о новостях.
        /// </summary>
        public static string NewsAndActionsLabel3 {
            get {
                return ResourceManager.GetString("NewsAndActionsLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ассортимент продукции.
        /// </summary>
        public static string ProductAssort1 {
            get {
                return ResourceManager.GetString("ProductAssort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хотите узнать об ассортименте нашей продукции? Тогда скорее нажимайте на кнопку, чтобы с ним ознакомиться..
        /// </summary>
        public static string ProductAssort2 {
            get {
                return ResourceManager.GetString("ProductAssort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ассоритмент продукции.
        /// </summary>
        public static string ProductAssort3 {
            get {
                return ResourceManager.GetString("ProductAssort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы от клиентов.
        /// </summary>
        public static string QuestLabel1 {
            get {
                return ResourceManager.GetString("QuestLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть какой-то вопрос? Задайте его нам через специальную форму и мы обязательно вам на него ответим..
        /// </summary>
        public static string QuestLabel2 {
            get {
                return ResourceManager.GetString("QuestLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать вопрос.
        /// </summary>
        public static string QuestLabel3 {
            get {
                return ResourceManager.GetString("QuestLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальные предложения.
        /// </summary>
        public static string SpecialOfferLabel {
            get {
                return ResourceManager.GetString("SpecialOfferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в наш интернет-магазин Alutech Shop.
        /// </summary>
        public static string WelcomeLabel1 {
            get {
                return ResourceManager.GetString("WelcomeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы заботимся о каждом клиенте, кто заходит в наш интернет-магазин. Чтобы ознакомится с нами поближе, кликните по кнопке!.
        /// </summary>
        public static string WelcomeLabel2 {
            get {
                return ResourceManager.GetString("WelcomeLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узнать более.
        /// </summary>
        public static string WelcomeLabel3 {
            get {
                return ResourceManager.GetString("WelcomeLabel3", resourceCulture);
            }
        }
    }
}
