//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlutechShopDiploma.Resources.Views.Purchase {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class List {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlutechShopDiploma.Resources.Views.Purchase.List", typeof(List).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начисление на бон. счёт.
        /// </summary>
        public static string AddOrderLabel {
            get {
                return ResourceManager.GetString("AddOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! Списание с бонусного счёта осуществляйте только после полного редактирования заказа. В случае, если вы спишете средства с бонусного счёта, а затем начнёте редактировать заказ, денежные средства с бонусного счёта учтены не будут..
        /// </summary>
        public static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! После заполнения данной формы вы оформите заказ, который нельзя будет уже отредактировать..
        /// </summary>
        public static string AttentionLabel {
            get {
                return ResourceManager.GetString("AttentionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша корзина.
        /// </summary>
        public static string BasketLabel {
            get {
                return ResourceManager.GetString("BasketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зачисления на бонусный счёт.
        /// </summary>
        public static string BonusesTableLabel {
            get {
                return ResourceManager.GetString("BonusesTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string ChangeBtnLabel {
            get {
                return ResourceManager.GetString("ChangeBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить на:.
        /// </summary>
        public static string ChangeLabel {
            get {
                return ResourceManager.GetString("ChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        public static string CostLabel {
            get {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сделать заказ.
        /// </summary>
        public static string CreateOrderLabel {
            get {
                return ResourceManager.GetString("CreateOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на р..
        /// </summary>
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша корзина пуста..
        /// </summary>
        public static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас в корзине:.
        /// </summary>
        public static string InBasletLabel {
            get {
                return ResourceManager.GetString("InBasletLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шт..
        /// </summary>
        public static string ItemsLabel {
            get {
                return ResourceManager.GetString("ItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция.
        /// </summary>
        public static string OperationLabel {
            get {
                return ResourceManager.GetString("OperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма покупок и % отчисления на бонусный счёт.
        /// </summary>
        public static string OrdersSumLabel {
            get {
                return ResourceManager.GetString("OrdersSumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупка.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма покупки, руб..
        /// </summary>
        public static string PurchaseTableLabel {
            get {
                return ResourceManager.GetString("PurchaseTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание с бон. счёта.
        /// </summary>
        public static string SpendsOrderLabel {
            get {
                return ResourceManager.GetString("SpendsOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зачисление на бонусный счёт, %.
        /// </summary>
        public static string SumBonusesTableLabel {
            get {
                return ResourceManager.GetString("SumBonusesTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма начисления.
        /// </summary>
        public static string SumBonusLabel {
            get {
                return ResourceManager.GetString("SumBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате.
        /// </summary>
        public static string ToPayLabel {
            get {
                return ResourceManager.GetString("ToPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая сумма покупки.
        /// </summary>
        public static string TotalSumOrder {
            get {
                return ResourceManager.GetString("TotalSumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать бонусы.
        /// </summary>
        public static string UseBonusLabel {
            get {
                return ResourceManager.GetString("UseBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш бонусный счёт.
        /// </summary>
        public static string YourBonusAmountLabel {
            get {
                return ResourceManager.GetString("YourBonusAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши покупки.
        /// </summary>
        public static string YourPurchasesLabel {
            get {
                return ResourceManager.GetString("YourPurchasesLabel", resourceCulture);
            }
        }
    }
}
