//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlutechShopDiploma.Resources.Views.GoodItem {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CartItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CartItem() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlutechShopDiploma.Resources.Views.GoodItem.CartItem", typeof(CartItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на здесь.
        /// </summary>
        public static string ActionLink {
            get {
                return ResourceManager.GetString("ActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы заблокированы по причине грубого нарушения правил написания комментариев. Эта функция недоступна заблокированным пользователям. Пожалуйста, обратитсь в службу поддержки для уточнения подробностей.Обратиться в поддержку можно.
        /// </summary>
        public static string BlockInfo1 {
            get {
                return ResourceManager.GetString("BlockInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Также можете подать заявку на разблокировку со своего аккаунта. Для этого щёлкнете.
        /// </summary>
        public static string BlockInfo2 {
            get {
                return ResourceManager.GetString("BlockInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Затем перейдите в раздел &apos;Моя статистика&apos;.
        /// </summary>
        public static string BlockInfo3 {
            get {
                return ResourceManager.GetString("BlockInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характиеристика.
        /// </summary>
        public static string CharLabel {
            get {
                return ResourceManager.GetString("CharLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие характеристики.
        /// </summary>
        public static string CommonChar {
            get {
                return ResourceManager.GetString("CommonChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на р..
        /// </summary>
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличие скидки.
        /// </summary>
        public static string DiscAvailableLabel {
            get {
                return ResourceManager.GetString("DiscAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скидка.
        /// </summary>
        public static string DiscountLabel {
            get {
                return ResourceManager.GetString("DiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, ваша оценка уже учтена за этот товар. Вы можете её отменить, нажав.
        /// </summary>
        public static string ExistMarkLabel {
            get {
                return ResourceManager.GetString("ExistMarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество товара на складе.
        /// </summary>
        public static string GoodAmmountLabel {
            get {
                return ResourceManager.GetString("GoodAmmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание товара.
        /// </summary>
        public static string GoodDescrLabel {
            get {
                return ResourceManager.GetString("GoodDescrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценить товар.
        /// </summary>
        public static string MarkGoodLabel {
            get {
                return ResourceManager.GetString("MarkGoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, данного товара нет на складе..
        /// </summary>
        public static string NoGood {
            get {
                return ResourceManager.GetString("NoGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, подобных товаров пока нет..
        /// </summary>
        public static string NoSimGoodLabel {
            get {
                return ResourceManager.GetString("NoSimGoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string ReviewsLabel {
            get {
                return ResourceManager.GetString("ReviewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подобные товары.
        /// </summary>
        public static string SimilarGoodsLabel {
            get {
                return ResourceManager.GetString("SimilarGoodsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические характеристики.
        /// </summary>
        public static string TechCharLabel {
            get {
                return ResourceManager.GetString("TechCharLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотры.
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
